var EmployeesModels = require("../models/EmployeesModels").EmployeesModels;
module.exports = (app) => {

    // find all data
    app.get('/employees',(req, res) => {
        EmployeesModels.find({}, (err, employees) => {
            if (err)
            return res.send(err);
            res.json(employees)
        })
    })

    // find data by uniqe id generated by mongodb
    app.get('/employees/:id', (req, res) => {
        EmployeesModels.find({"_id": req.params.id}, (err, employees) => {
            if (err)
            return res.send(err)
            res.json(employees)
        })
    })

    // add data route to register
    app.post('/employees/register', (req, res) => {
        const employees = new EmployeesModels()
        employees.emp_no = req.body.emp_no
        employees.birth_date = req.body.birth_date
        employees.first_name = req.body.first_name
        employees.last_name = req.body.last_name
        employees.gender = req.body.gender
        employees.hire_date = req.body.hire_date

        console.log(req.body.first_name)
        employees.save((err, employees) => {
            if(err)
            return res.send(err)
            res.json({'status':'OK!', data:employees})
        })
    })

    // edit data on edit's route
    app.put('/employees/edit', (req, res) => {
        EmployeesModels.findById(req.body.id, (err, employees) => {
            if(err)
            return res.send(err)
            employees.emp_no = req.body.emp_no
            employees.birth_date = req.body.birth_date
            employees.first_name = req.body.first_name
            employees.last_name = req.body.last_name
            employees.gender = req.body.gender
            employees.hire_date = req.body.hire_date

            employees.save((err, employees) => {
                if(err)
                return res.send(err)
                res.json({'status':'OK!', data:employees})
            })
        })
    })

    // delete data by unique id generated by mongodb
    app.delete('/employees/delete/:id', (req, res) => {
        EmployeesModels.findById(req.params.id, (err, employees) => {
            if(err)
            return res.send(err)
            employees.remove((err) => {
                if(err)
                return res.send(err)
                res.json({'status':'OK!'})
            })
        })
    })


}